export default {
  currency: '€',
  headerTitle: 'Foodlea',
  onboardingTitle1: 'Food Corner is Where Your Comfort Food Lives',
  onboardingTitle2: 'Find your Comfort Food here',
  onboardingSubtitle1: 'Enjoy a fast and smooth food delivery at your doorstep',
  onboardingSubtitle2:
    'Here You Can find a chef or dish for every taste and color. Enjoy!',
  login: 'Log in',
  signup: 'Sign up',
  or: 'OR',
  start: "Sign in",
  loginText: 'Sign in to continue',
  phonePlaceholder: 'Phone number',
  emailPlaceholder: 'Enter your email',
  password: 'Password',
  noAccount: "Don't have an account, ",
  signupnow: 'SIGNUP NOW',
  loginnow: 'LOGIN NOW',
  signupHeading: 'Get ready to enjoy food services',
  firstName: 'First Name',
  lastName: 'Last Name',
  verify: 'VERIFY ACCOUNT',
  restaurant: 'Restuarant',
  veficationDescription:
    'We have sent you a 4 digit verification code (OTP) on your provided email and Phone Number',
  passwordHeading: 'ALMOST DONE',
  passwordSubHeading: 'Set your Security to Get Sign Up',
  confirmPassword: 'Confirm Password',
  forgot: 'Reset Password',
  forgotPassword: 'Forgot your password?',
  forgotConfermation: ' Password Confermation',
  reset: 'Enter your email to receive reset password link',
  resetButton: 'RESET',
  bannerHeading: 'Wait, double ham burger?',
  bannerSubheading: 'We are here with the best double ham burger!',
  orderBtn: 'ORDER NOW',
  next: 'Next',
  placeOrder: 'Place Order',
  delivery: 'Delivery',
  pickup: 'Pick Up',
  dinein: 'Dine In',
  contactInfo: 'Contact Info',
  deliveryTime: 'Delivery Time',
  pickUpDateTime: 'Pick Up Date and Time',
  wallet: 'Wallet',
  card: 'Card',
  cash: 'Cash',
  createPassword: 'Create new password',
  noPeoplePlaceholder: 'No. of People',
  datePlaceholder: 'Date',
  timePlaceholder: 'Start Time',
  contactNoPlaceholder: 'Contact No.',
  about: 'About',
  addAdress: 'Add Address',
  selectLocation: 'Selected Location',
  street: 'Street',
  floorBuilding: 'Floor # / Building',
  noteToRider: 'Note to Rider',
  saveAddress: 'Save Address',
  ratingUpdated: 'Rating Updated',
  addresses: 'Addresses',
  selectLocationa: 'Select Location',
  selectLocationb: 'SELECT LOCATION',
  categories: 'Categories',
  kugisakiNobara: 'Kugisaki Nobara',
  favourite: 'Favourite',
  settings: 'Settings',
  notifications: 'Notifications',
  logOut: 'Log Out',
  filters: 'Filters',
  postcode: 'Postcode',
  nearestMe: 'Nearest Me',
  costHightoLow: 'Cost High to Low',
  costLowtoHigh: 'Cost Low to High',
  mostPopular: 'Most Popular',
  homeScreen: 'Home Screen',
  extraMayo: 'Eg. Extra Mayo',
  addToCart: 'Add To Cart',
  myRewards: 'My Rewards',
  goldCardRewarded: 'Gold Card Rewarded',
  myAddress: 'My Address',
  homeAdress: 'Current Address: Home',
  myDetails: 'My Details',
  changePassword: 'Change Password',
  profile: 'Profile',
  rate: 'Rate',
  feedback: 'Leave Feedback',
  allRestaurants: 'All Restaurants',
  reviews: 'Reviews',
  myDetailsa: 'My Details',
  firstNamea: 'First Name',
  lastNamea: 'Last Name',
  email: 'Email',
  emailSmallLatter:'email',
  mobile: 'Mobile No.',
  update: 'Update',
  orderTitle: 'Orders',
  payments: 'Payments',
  OrderDetail: 'Order Detail',
  minOrder: 'Min. Order:£',
  maxOrder: 'Max. Order:£',
  deliveryCharges: 'Delivery Charges: £',
  support: 'Support',
  miles:'miles',
  processedOrder: 'Your order #877787 has been proceeded',
  totalOrderAmount: 'Your total amount is $676',
  justNow: 'Just Now',
  orderId: 'Order ID :',
  nisaSultan :'nisa Sultan',
  nisaSultanAddress: 'MM alam road nisa sultan',
  discountReward: '10% discount on all Burgers, Pizza, Biryani items',
  subTotal: ' Subtotal',
  deliveryText: 'Delivery (incl. tax)',
  totalCharges: 'Total Charges',
  viewYourCart: 'View your Cart',
  openingTimings: 'Opening Timings',
  openinngDays: 'Opening Days',
  lorem1: 'Lorem ipsum dolor sit amet',
  lorem2: 'The lorem ipsum is based on De finibus bonorum et malorum . The lorem ipsum gets its name from the Latin phrase',
  lorem3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim adminim veniam, quis nostrud exercitation ullamco laboris nisi utaliquip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum dolore eu fugiat nullapariatur. Excepteur sint occaecat cupidatat non proident, sunt inculpa qui officia deserunt mollit anim id est laborum.',
  orderAddress: 'CB 81/84 H no. 60 Islamabad',
  changeOrAdd: 'Address',
  reservetable: 'Reserve Table',
  select: 'Select',
  paymentMethod: 'Payment Method',
  changePassword: 'Change Password',
  changePasswordText: 'Please change your password here',
  noDataAvailable: ' No data available!',
  sortBy: 'Sort By',
  orderBy: 'Order By',
  cuisines: 'Cuisines',
  price: 'Price',
  inventory: 'Inventory',
  currentLocation: 'Current Location',
  foodDetail: 'This beef burger use 100% quality beef with sliced tomatoes,cucumbers, vegetables and onions...',
  variation: 'Variation',
  description: 'Description',
  addNotes: 'Add Notes',
  totalBill: 'Total x',
  extras: 'Extras',
  rewardTitle: 'Rewards',
  deliveredTo: 'Delivered to',
  branch: 'Branch',
  dealAnyone: 'Deal Anyone',
  history: 'History',
  myAccount: 'My Account',
  paid: 'Paid',
  addons: 'Addons',
  x: 'x',
  addPayment: 'Add Payment',
  saveCard: 'Save Card',
  thankYou: 'THANKYOU!',
  enjoyYourMeal: 'Enjoy your meal!',
  rateYourFood: 'Please rate your food!',
  feedbackText: 'Feedback',
  passwordChanged: 'Password Changed',
  loginSuccess: 'You have successfully changed your password! Try your new login.',
  submit: 'Submit',
  skip: 'Skip',
  skipCapitalCase: 'SKIP',
  clearCartText: ' Wish to go back? Your cart will be cleared.',
  clearCart : 'Clear Cart',
  gender: 'Gender',
  home: 'Home',
  work: 'Work',
  other: 'Other',
  item: 'item',
  needSupport: 'Need Support?',
  solveTheIssue: 'Lets solve the issue',
  itemsTotal: 'Items Total',
  label: 'Lable',
  cart: 'Cart',
  promoCode: 'Promo Code',
  placeOrderCardText1: 'YOU HAVE SUCCESSFULLY',
  placeOrderCardText2: 'PLACED YOUR ORDER',
  oldPassword: 'Old Password',
  newPassword: 'New password',
  confirmPassword: 'Confirm Password',
  changePassword: 'Change Password',
  changePasswordCardText1: 'YOU HAVE SUCCESSFULLY',
  changePasswordCardText2: 'CHANGED YOUR PASSWORD',
  celories250: '250 kcal',
  search: 'Search...',
  mobNumber: '4242 4242 4242 4242',
  star: 'star',
  send: 'Send',
  fourPoint9: '4.9',
  twentyMin: '20 min',
  facebookEmailPostFix:'@foodlea.com',
  emailSent: 'Email Sent',
  passwordResetEmail: 'We have sent you an email with reset password link. Open and recover your password',
};
